### ISSUE TITLE
Add folders and examples for storing cloned git repos

### ISSUE THREAD

**Issue by fionera** [roboyoshi/datacurator-filetree#28]
I dont know where it should have its root but the scheme of golang seems like a good idea like: src/github.com/Example/Repo

**Comment by roboyoshi** [comment]
Hey @fionera , thanks again for the input. I'd say the first place for this is the `root/web` directory which has a similar structure to what you describe. Since Repositories often resemble code for software, my 2nd best guess would be to but it in `root/software/` Maybe add another sub-directory for `open-source` or `source-code` or `repositories`.

**Comment by fionera** [comment]
I would go for Option B since the web dir is mostly for mirrors and repos would be hard to identify

**Comment by roboyoshi** [comment]
@fionera yes sure, I'll add both. You may have a general-purpose scraper that downloads the repo into (A), and you may have git cloned repositories or standalone repos that go into (B).

**Comment by roboyoshi** [comment]
I think this is a nice issue for the hacktoberfest, because we are probably cloning a lot of git repos right now :)
