### ISSUE TITLE
Add scene-centric branch and folder structure

### ISSUE THREAD

**Issue by fionera** [roboyoshi/datacurator-filetree#29]
What about downloaded Torrents that are in Scene format. I personally unrar them and move them to `root/torrent/video/movies`. Since I didnt had a better Idea. Maybe you have one :D

**Comment by roboyoshi** [comment]
Torrents can either be integrated into the structure, if they allow it - or kept seperate in a temporary folder, where one might sort them and then integrate into the structure.

Scene Releases are kinda special, because you would sort them into something like ´root/video/movies/` directly. I'd actually say that is indeed the way to go.

If your collection is more focused on the `scene` archives, then I'd say create a new `root` for this and use the scene rules as a reference (using [scenerules.org](https://scenerules.org/) for example). I'll use this in order to create a new Branch, that does this.

TODO:
- Create `scene` branch
- Create new root with contents based on the scenerules (see link above and other scene archives).

**Comment by roboyoshi** [comment]
A few resources so far:
- http://i1209.photobucket.com/albums/cc394/fsfmirror/images2/pubstro_1.jpg
- https://www.youtube.com/watch?v=kretML1ZG-Y (some folders to see at ~2:10)
- http://predb.me
- https://www.szenebox.org/images/_imported/2016/02/5.jpg
- https://www.xrel.to/releases.html

Folder Structure is either splitted by language:
```
GERMAN
ENGLISH
FRENCH
ITALIAN
SPANISH
```

or just by release type:

```
movie/{sd,hd}
tv/{sd,hd}
games/{xbox,nintendo,playstation,pc}
music
```

I'll check the sources out, create a few test trees and see how that goes..

**Comment by roboyoshi** [comment]
Scene branch was added a while ago and I added a link to the readme now. Hope that helps.
