### ISSUE TITLE
Rename tv-series to tv-shows

### ISSUE THREAD

**Issue by fionera** [roboyoshi/datacurator-filetree#30]
I feel like TV-Shows is more suited as folder name, what do you think?

**Comment by roboyoshi** [comment]
IMO that actually depends on language/localization what is preferred.
I chose `series`, because that's the term my research defined as correct:

- https://forum.wordreference.com/threads/tv-show-vs-tv-series.3296306/

> I would use "TV series" for "The Game of Thrones", and similar programmes, because the story contains multiple episodes. [..]
> "TV show" is just a more general term, which doesn't distinguish whether a programme is a series or a one-off.

> "Show" refers to the whole thing [..]

- https://www.quora.com/What-is-the-difference-between-a-TV-series-and-a-TV-show
> In the United States, a TV show is a single episode of television. [...]
> [..] A television "series" is all of the shows (episodes) of a program [...]
> In the UK, the terminology is different. They use "series" to mean what we in the US would probably call "seasons."

- https://en.wikipedia.org/wiki/Television_show (important bits marked **bold** by me)
> A **television show** might also be called a television program (British English: programme), especially if it **lacks a narrative structure**. A **television series** is usually released in episodes that **follow a narrative**, and are usually **divided into seasons** (US and Canada) **or series** (UK) – yearly or semiannual sets of new episodes. A show with a limited number of episodes may be called a miniseries, serial, or limited series. A one-time show may be called a "special".

**Comment by roboyoshi** [comment]
I'm adding a `wontfix` here, because the folder is valid, but I'm open for discussing this further. I think it would make sense to include the explanation (tv-show = no narrative structure; tv-series = follow narrative structure) into the README for the tv section, as well as showing the multiple options one might get with choosing one or the other.
