### ISSUE TITLE
Split Games by OS

### ISSUE THREAD

**Issue by fionera** [roboyoshi/datacurator-filetree#32]
When you have games for multiple Operating Systems for PCs they should be seperated, right?

**Comment by roboyoshi** [comment]
Hm.. that's a tricky one.. I'm no expert in this area so I'll need to check on this. AFAIK it depends on the architecture (x86/x64) and on the system (nix/win/mac). But If a Game only works in ubuntu, but not on Fedora (or vice-versa) then we'll get a lot of folders.. I'd keep it simple at first, but keep this issue open until someone steps in with more knowledge on the topic.

**Comment by fionera** [comment]
I would differentiate between *nix Systems but atleast split to Win/Mac/Nix

**Comment by GuilhermeHideki** [comment]
I personally don't like to split between OSes (at the top folder, like `games/PC/Win`) because I don't have too many PC games. Also, some games could be played in multiples OSes (e.g. Java JARs). Well, you could just create a "Java OS" folder.

In this case, I use the "MusicBrainz style" of `/{release group}/{release}`, so `game/game-GOTY-x64-win` or `game/game-linux` would be ok to me.

**Comment by strafer** [comment]
For archiving games, I organize by OS since I have a dual-booting Hackintosh. I play games both on macOS and Windows, so it makes sense for me to separate game installers by OS.
