### ISSUE TITLE
Lack of a 'wip' branch

### ISSUE THREAD

**Issue by Thunkstation** [roboyoshi/datacurator-filetree#39]
Not only would it be useful to commit changes to there rather than straight to master, it's also already covered in documentation (see CONTRIBUTING.md) but was apparently deleted? Regardless, it would definitely be a useful addition for development.

**Comment by roboyoshi** [comment]
Yes I deleted it, because I felt the exact opposite. Having a `develop`/`wip` branch is typical for software-dev (Classic Git Flow), but I don't see why it would be necessary here? When someone creates a PR and it's accepted, then it's pretty much approved and can be released to the public right away. So I changed it to `master` only. There are other branches for certain features, but I don't feel like changing it back.

**Comment by Thunkstation** [comment]
Ah ok, fair enough. I can kind of see now why it wouldn't really be necessary. Thanks for explaining.
