### ISSUE TITLE
Proposal: singular vs plural naming scheme & lower case for global structure

### ISSUE THREAD

**Issue by codesnippy** [roboyoshi/datacurator-filetree#45]
Best Roboyoshi,

I really love this project.

I have a few proposals.
1. make all folder names singular vs plural.
This makes reading a tree structure more human sensible.
so e.g.: /root/video/movie/The Godfather (1972)  VS  /root/videos/movies/The Godfather (1972)

2. make all the global folder names lowercase
This makes it far easier to get to these folder via command line. Especially in case senitive operating systems. 
so e.g.:  /root/software/operating systems/User Level  VS  /root/Software/Operating Systems/User Level

With kind regards,
Wouter

**Comment by roboyoshi** [comment]
Hey @codesnippy,
thanks a lot for the input. This is actually the way I had intended to use it, but the community was driving me towards the current scheme. I respect that and try to find a good middleground.

Regarding (1):
I'm coming from web development and restful service URIs are usually plural 
( http://service:8080/api/books/123 ), which is considered "Best Practice". It's also partially based on the Filesystem "defaults", which is plural. If you install Windows/Mac/Linux today - all use the plural form of "Videos" in their respective "user" folder.

But the filetree is not consistent right now and I will try to fix that.

Regarding (2):
I agree to lowercase up to level 2 of the hierarchy. Everything beyond that is irrelevant to me in terms of consistency, capitalization, plural vs. singular, etc - because I simply can't enforce it for the whole community.

**Comment by roboyoshi** [comment]
Closing Notes: For now the filetree will stay with plural names unless the community collectively forces me to change this.
